apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

configMapGenerator:
  - name: argocd-scripts
    files:
      - add-to-argocd.sh
      - remove-from-argocd.sh
    options:
      disableNameSuffixHash: true