---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: capd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: capd Clusters & Apps
  destinations:
  - namespace: '*'
    name: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/mgmt-template.git
