apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./previewenv-events
  - previewenv-appset.yaml
  - preview-appdeployment.yaml
  ## to use repo-appsets, we need the Argocd Application CRDs on the Target cluster
  # - preview-repo-appset.yaml