apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: capd-add-template
  namespace: argo
spec:
  templates:
    - name: frigg-builder-pod
      container:
        image: ghcr.io/patricklaabs/frigg-builder:1.0.0
        command: ["/bin/sh", "-c", "/etc/argocd-scripts/add-to-argocd.sh {{workflow.parameters.cluster}}"]
        volumeMounts:
        - name: argocd-scripts
          mountPath: /etc/argocd-scripts/
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: argocd-login
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: argocd-login
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
      volumes:
      - name: argocd-scripts
        configMap:
          name: argocd-scripts
          defaultMode: 0777