apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: capd-add
  namespace: argo
spec:
  template:
    serviceAccountName: argocd-workflow
  eventBusName: capd-add
  resource:
    capd-add:
      namespace: default
      group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      resource: dockerclusters
      eventTypes:
        - ADD
      filter:
        afterStart: true