---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application-cdk8s
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/mgmt-template.git
    path: app-deployments/components/sample-application-cdk8s
    targetRevision: main
    plugin:
      name: cdk8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true